# Generated by Django 3.2 on 2023-01-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=254)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('artist_bio', models.TextField()),
                ('artist_link_bandcamp', models.URLField(blank=True, max_length=1024, null=True)),
                ('artist_link_spotify', models.URLField(blank=True, max_length=1024, null=True)),
                ('artist_link_soundcloud', models.URLField(blank=True, max_length=1024, null=True)),
                ('bandcamp_counter', models.IntegerField(default=0)),
                ('spotify_counter', models.IntegerField(default=0)),
                ('soundcloud_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
