# Generated by Django 3.2 on 2023-01-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=254)),
                ('track_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('track_bio', models.TextField()),
                ('track_link_bandcamp', models.URLField(blank=True, max_length=1024, null=True)),
                ('track_link_spotify', models.URLField(blank=True, max_length=1024, null=True)),
                ('track_link_soundcloud', models.URLField(blank=True, max_length=1024, null=True)),
                ('track_bandcamp_counter', models.IntegerField(default=0)),
                ('track_spotify_counter', models.IntegerField(default=0)),
                ('track_soundcloud_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
