# Generated by Django 3.2 on 2023-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_latestmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='latestmusic',
            name='track_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
