# Generated by Django 3.2 on 2023-01-19 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20230117_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestmusic',
            old_name='track_link_bandcamp',
            new_name='track_link',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_link_bandcamp',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_link_soundcloud',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_link_spotify',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bandcamp_counter',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='soundcloud_counter',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify_counter',
        ),
        migrations.RemoveField(
            model_name='latestmusic',
            name='track_bandcamp_counter',
        ),
        migrations.RemoveField(
            model_name='latestmusic',
            name='track_link_soundcloud',
        ),
        migrations.RemoveField(
            model_name='latestmusic',
            name='track_link_spotify',
        ),
        migrations.RemoveField(
            model_name='latestmusic',
            name='track_soundcloud_counter',
        ),
        migrations.RemoveField(
            model_name='latestmusic',
            name='track_spotify_counter',
        ),
        migrations.AddField(
            model_name='artist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestmusic',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
